#!/usr/bin/env bash
# VPN Control Plane Agent Installer
# Supports: Ubuntu 20.04 / 22.04 / 24.04
# Usage:
#   curl -fsSL https://YOUR_PUBLIC_URL/install.sh | sudo bash -s -- \
#     --control-plane https://api.yourpanel.com \
#     --join-token jt_xxxxx \
#     --server-id srv_xxxxx \
#     --agent-version latest
#
# Manual status:
#   sudo vpn-control-agent status
#
# Uninstall:
#   sudo vpn-control-agent uninstall

set -Eeuo pipefail

AGENT_NAME="vpn-control-agent"
AGENT_USER="vpnagent"
AGENT_GROUP="vpnagent"
INSTALL_DIR="/opt/${AGENT_NAME}"
CONFIG_DIR="/etc/${AGENT_NAME}"
LOG_DIR="/var/log/${AGENT_NAME}"
STATE_DIR="/var/lib/${AGENT_NAME}"
SYSTEMD_FILE="/etc/systemd/system/${AGENT_NAME}.service"
WRAPPER_BIN="/usr/local/bin/${AGENT_NAME}"

# Change this to your real release host before publishing.
DEFAULT_RELEASE_BASE_URL="https://agent.yourdomain.com/releases"
DEFAULT_AGENT_VERSION="latest"
DEFAULT_AGENT_BINARY_NAME="agent-linux-amd64"

CONTROL_PLANE_URL=""
JOIN_TOKEN=""
SERVER_ID=""
AGENT_ID=""
AGENT_TOKEN=""
PROVIDER="unknown"
PROVIDER_ACCOUNT_ID=""
REGION=""
ENVIRONMENT="production"
RELEASE_BASE_URL="${DEFAULT_RELEASE_BASE_URL}"
AGENT_VERSION="${DEFAULT_AGENT_VERSION}"
AGENT_BINARY_NAME="${DEFAULT_AGENT_BINARY_NAME}"
SKIP_REGISTER="false"
ALLOW_ROOT_AGENT="true"

log() { printf '\033[1;32m[agent-install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[agent-install][warn]\033[0m %s\n' "$*" >&2; }
err() { printf '\033[1;31m[agent-install][error]\033[0m %s\n' "$*" >&2; }

usage() {
  cat <<USAGE
VPN Control Plane Agent Installer

Required:
  --control-plane URL       Control Plane API base URL, e.g. https://api.yourpanel.com
  --join-token TOKEN        One-time join token generated by Control Plane

Optional:
  --server-id ID            Server ID created by Control Plane
  --provider NAME           Provider name: hetzner, digitalocean, aws, cherry, manual
  --provider-account ID     Provider account ID in Control Plane
  --region REGION           Provider region/datacenter
  --environment ENV         production/staging/dev. Default: production
  --release-base-url URL    Agent binary release base URL. Default: ${DEFAULT_RELEASE_BASE_URL}
  --agent-version VERSION   Agent version or latest. Default: latest
  --binary-name NAME        Binary filename. Default: ${DEFAULT_AGENT_BINARY_NAME}
  --skip-register           Install service without calling register endpoint
  --no-root-agent           Run service as vpnagent user instead of root. Requires sudo policy for privileged jobs.
  --help                    Show this help

Examples:
  curl -fsSL https://agent.example.com/install.sh | sudo bash -s -- \\
    --control-plane https://api.example.com \\
    --join-token jt_abc \\
    --server-id srv_123 \\
    --provider hetzner

USAGE
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "This installer must be run as root. Use sudo."
    exit 1
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --control-plane) CONTROL_PLANE_URL="${2:-}"; shift 2 ;;
      --join-token) JOIN_TOKEN="${2:-}"; shift 2 ;;
      --server-id) SERVER_ID="${2:-}"; shift 2 ;;
      --provider) PROVIDER="${2:-}"; shift 2 ;;
      --provider-account|--provider-account-id) PROVIDER_ACCOUNT_ID="${2:-}"; shift 2 ;;
      --region) REGION="${2:-}"; shift 2 ;;
      --environment) ENVIRONMENT="${2:-}"; shift 2 ;;
      --release-base-url) RELEASE_BASE_URL="${2:-}"; shift 2 ;;
      --agent-version) AGENT_VERSION="${2:-}"; shift 2 ;;
      --binary-name) AGENT_BINARY_NAME="${2:-}"; shift 2 ;;
      --skip-register) SKIP_REGISTER="true"; shift ;;
      --no-root-agent) ALLOW_ROOT_AGENT="false"; shift ;;
      --help|-h) usage; exit 0 ;;
      *) err "Unknown argument: $1"; usage; exit 1 ;;
    esac
  done

  if [[ -z "${CONTROL_PLANE_URL}" ]]; then
    err "Missing --control-plane"
    usage
    exit 1
  fi

  if [[ "${SKIP_REGISTER}" != "true" && -z "${JOIN_TOKEN}" ]]; then
    err "Missing --join-token"
    usage
    exit 1
  fi

  CONTROL_PLANE_URL="${CONTROL_PLANE_URL%/}"
  RELEASE_BASE_URL="${RELEASE_BASE_URL%/}"
}

check_os() {
  if [[ ! -f /etc/os-release ]]; then
    err "Unsupported OS: /etc/os-release not found"
    exit 1
  fi

  # shellcheck disable=SC1091
  source /etc/os-release

  if [[ "${ID:-}" != "ubuntu" ]]; then
    err "Unsupported OS: ${PRETTY_NAME:-unknown}. This installer currently supports Ubuntu only."
    exit 1
  fi

  case "${VERSION_ID:-}" in
    20.04|22.04|24.04) log "Detected ${PRETTY_NAME}" ;;
    *) warn "Ubuntu ${VERSION_ID:-unknown} is not officially tested. Continuing." ;;
  esac
}

install_deps() {
  export DEBIAN_FRONTEND=noninteractive
  log "Installing dependencies"
  apt-get update -y
  apt-get install -y ca-certificates curl jq tar gzip coreutils systemd iproute2 net-tools lsof
}

create_user_and_dirs() {
  if ! getent group "${AGENT_GROUP}" >/dev/null; then
    groupadd --system "${AGENT_GROUP}"
  fi

  if ! id "${AGENT_USER}" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin --gid "${AGENT_GROUP}" "${AGENT_USER}"
  fi

  mkdir -p "${INSTALL_DIR}" "${CONFIG_DIR}" "${LOG_DIR}" "${STATE_DIR}"
  chmod 0755 "${INSTALL_DIR}" "${CONFIG_DIR}" "${LOG_DIR}" "${STATE_DIR}"
  chown -R "${AGENT_USER}:${AGENT_GROUP}" "${LOG_DIR}" "${STATE_DIR}"
}

agent_download_url() {
  if [[ "${AGENT_VERSION}" == "latest" ]]; then
    printf '%s/latest/%s' "${RELEASE_BASE_URL}" "${AGENT_BINARY_NAME}"
  else
    printf '%s/%s/%s' "${RELEASE_BASE_URL}" "${AGENT_VERSION}" "${AGENT_BINARY_NAME}"
  fi
}

download_agent() {
  local url
  url="$(agent_download_url)"
  log "Downloading agent binary from ${url}"

  if ! curl -fL --retry 5 --retry-delay 2 --connect-timeout 15 "${url}" -o "${INSTALL_DIR}/agent.tmp"; then
    warn "Could not download agent binary. Installing placeholder agent for bootstrap validation."
    cat > "${INSTALL_DIR}/agent.tmp" <<'PLACEHOLDER'
#!/usr/bin/env bash
set -euo pipefail
CONFIG_FILE="/etc/vpn-control-agent/config.env"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi
cmd="${1:-run}"
case "$cmd" in
  run)
    echo "vpn-control-agent placeholder is running. Replace /opt/vpn-control-agent/agent with real binary." >&2
    while true; do
      echo "$(date -Is) placeholder heartbeat: CONTROL_PLANE_URL=${CONTROL_PLANE_URL:-unset} SERVER_ID=${SERVER_ID:-unset}" >> /var/log/vpn-control-agent/agent.log
      sleep 30
    done
    ;;
  health)
    echo '{"status":"placeholder","service":"running","message":"real agent binary not installed yet"}'
    ;;
  version)
    echo "placeholder"
    ;;
  *)
    echo "unknown command: $cmd" >&2
    exit 2
    ;;
esac
PLACEHOLDER
  fi

  mv "${INSTALL_DIR}/agent.tmp" "${INSTALL_DIR}/agent"
  chmod 0755 "${INSTALL_DIR}/agent"
  chown root:root "${INSTALL_DIR}/agent"
}

write_config() {
  log "Writing config"

  umask 077
  cat > "${CONFIG_DIR}/config.env" <<CONFIG
CONTROL_PLANE_URL="${CONTROL_PLANE_URL}"
SERVER_ID="${SERVER_ID}"
AGENT_ID="${AGENT_ID}"
AGENT_TOKEN="${AGENT_TOKEN}"
PROVIDER="${PROVIDER}"
PROVIDER_ACCOUNT_ID="${PROVIDER_ACCOUNT_ID}"
REGION="${REGION}"
ENVIRONMENT="${ENVIRONMENT}"
STATE_DIR="${STATE_DIR}"
LOG_DIR="${LOG_DIR}"
CONFIG_DIR="${CONFIG_DIR}"
CONFIG

  if [[ -n "${JOIN_TOKEN}" ]]; then
    cat > "${CONFIG_DIR}/join-token" <<TOKEN
${JOIN_TOKEN}
TOKEN
    chmod 0600 "${CONFIG_DIR}/join-token"
  fi

  chown -R root:root "${CONFIG_DIR}"
  chmod 0750 "${CONFIG_DIR}"
  chmod 0600 "${CONFIG_DIR}/config.env"
}

register_agent() {
  if [[ "${SKIP_REGISTER}" == "true" ]]; then
    warn "Skipping registration because --skip-register was provided"
    return 0
  fi

  log "Registering agent with Control Plane"

  local hostname machine_id primary_ip payload response status ok error
  hostname="$(hostname -f 2>/dev/null || hostname)"
  machine_id="$(cat /etc/machine-id 2>/dev/null || true)"
  primary_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"

  payload="$(jq -n \
    --arg joinToken "${JOIN_TOKEN}" \
    --arg serverId "${SERVER_ID}" \
    --arg hostname "${hostname}" \
    --arg machineId "${machine_id}" \
    --arg primaryIp "${primary_ip}" \
    --arg provider "${PROVIDER}" \
    --arg providerAccountId "${PROVIDER_ACCOUNT_ID}" \
    --arg region "${REGION}" \
    --arg environment "${ENVIRONMENT}" \
    --arg agentVersion "${AGENT_VERSION}" \
    '{joinToken:$joinToken, serverId:$serverId, hostname:$hostname, machineId:$machineId, primaryIp:$primaryIp, provider:$provider, providerAccountId:$providerAccountId, region:$region, environment:$environment, agentVersion:$agentVersion}' \
  )"

  set +e
  response="$(curl -fsS --retry 5 --retry-delay 2 \
    -H 'Content-Type: application/json' \
    -X POST "${CONTROL_PLANE_URL}/api/agent/register" \
    -d "${payload}" 2>/tmp/${AGENT_NAME}-register.err)"
  status=$?
  set -e

  if [[ ${status} -ne 0 ]]; then
    warn "Registration request failed. Service will still be installed. Error: $(cat /tmp/${AGENT_NAME}-register.err 2>/dev/null || true)"
    return 0
  fi

  ok="$(printf '%s' "${response}" | jq -r '.ok // false' 2>/dev/null || echo "false")"
  if [[ "${ok}" != "true" ]]; then
    error="$(printf '%s' "${response}" | jq -r '.error // .message // "registration failed"' 2>/dev/null || echo "registration failed")"
    err "Agent registration failed: ${error}"
    exit 1
  fi

  AGENT_ID="$(printf '%s' "${response}" | jq -r '.agentId // empty' 2>/dev/null || true)"
  AGENT_TOKEN="$(printf '%s' "${response}" | jq -r '.agentToken // .token // empty' 2>/dev/null || true)"
  if [[ -z "${AGENT_ID}" ]]; then
    err "Registration succeeded but response did not include agentId"
    exit 1
  fi

  if [[ -n "${AGENT_TOKEN}" ]]; then
    write_config
    cat > "${CONFIG_DIR}/agent-token" <<TOKEN
${AGENT_TOKEN}
TOKEN
    chmod 0600 "${CONFIG_DIR}/agent-token"
    chown root:root "${CONFIG_DIR}/agent-token"
    if ! grep -q '^AGENT_TOKEN="[^"]' "${CONFIG_DIR}/config.env"; then
      err "Agent registration succeeded but AGENT_TOKEN was not persisted to ${CONFIG_DIR}/config.env"
      exit 1
    fi
    log "Agent token saved"
  else
    err "Registration succeeded but response did not include agentToken/token"
    exit 1
  fi
}

write_systemd() {
  log "Writing systemd service"

  local service_user service_group
  if [[ "${ALLOW_ROOT_AGENT}" == "true" ]]; then
    service_user="root"
    service_group="root"
  else
    service_user="${AGENT_USER}"
    service_group="${AGENT_GROUP}"
  fi

  cat > "${SYSTEMD_FILE}" <<SERVICE
[Unit]
Description=VPN Control Plane Agent
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=${service_user}
Group=${service_group}
EnvironmentFile=${CONFIG_DIR}/config.env
ExecStart=${INSTALL_DIR}/agent run
Restart=always
RestartSec=5
KillSignal=SIGTERM
TimeoutStopSec=30
LimitNOFILE=1048576
WorkingDirectory=${INSTALL_DIR}
StandardOutput=append:${LOG_DIR}/agent.log
StandardError=append:${LOG_DIR}/agent.err.log

# Hardening. Keep flexible for protocol installers; tighten later per command permissions.
NoNewPrivileges=false
PrivateTmp=true
ProtectHome=true

[Install]
WantedBy=multi-user.target
SERVICE

  systemctl daemon-reload
  systemctl enable "${AGENT_NAME}" >/dev/null
}

write_wrapper() {
  cat > "${WRAPPER_BIN}" <<'WRAPPER'
#!/usr/bin/env bash
set -euo pipefail
SERVICE="vpn-control-agent"
INSTALL_DIR="/opt/vpn-control-agent"
CONFIG_DIR="/etc/vpn-control-agent"
cmd="${1:-status}"
case "$cmd" in
  status)
    systemctl status "$SERVICE" --no-pager || true
    ;;
  logs)
    journalctl -u "$SERVICE" -n "${2:-100}" --no-pager
    ;;
  restart)
    systemctl restart "$SERVICE"
    systemctl status "$SERVICE" --no-pager || true
    ;;
  health)
    "$INSTALL_DIR/agent" health
    ;;
  version)
    "$INSTALL_DIR/agent" version
    ;;
  uninstall)
    systemctl disable --now "$SERVICE" || true
    rm -f "/etc/systemd/system/${SERVICE}.service"
    systemctl daemon-reload
    rm -rf "$INSTALL_DIR" "$CONFIG_DIR" "/var/log/${SERVICE}" "/var/lib/${SERVICE}"
    rm -f "/usr/local/bin/${SERVICE}"
    echo "${SERVICE} uninstalled"
    ;;
  *)
    echo "Usage: vpn-control-agent {status|logs [n]|restart|health|version|uninstall}" >&2
    exit 2
    ;;
esac
WRAPPER
  chmod 0755 "${WRAPPER_BIN}"
}

start_service() {
  log "Starting ${AGENT_NAME}"
  systemctl restart "${AGENT_NAME}"
  sleep 2
  systemctl --no-pager --full status "${AGENT_NAME}" || true
}

first_health_report() {
  log "Running first local health snapshot"
  local service_status primary_ip disk_pct mem_total_mb payload token auth_header
  service_status="$(systemctl is-active "${AGENT_NAME}" || true)"
  primary_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  disk_pct="$(df -P / | awk 'NR==2 {gsub("%","",$5); print $5}' || true)"
  mem_total_mb="$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo 2>/dev/null || true)"

  payload="$(jq -n \
    --arg serverId "${SERVER_ID}" \
    --arg serviceStatus "${service_status}" \
    --arg primaryIp "${primary_ip}" \
    --arg diskPct "${disk_pct}" \
    --arg memTotalMb "${mem_total_mb}" \
    '{serverId:$serverId, agentService:$serviceStatus, primaryIp:$primaryIp, diskUsedPct:($diskPct|tonumber? // null), memoryTotalMb:($memTotalMb|tonumber? // null), timestamp:now|todate}' \
  )"

  token="${AGENT_TOKEN}"
  if [[ -z "${token}" && -f "${CONFIG_DIR}/config.env" ]]; then
    # shellcheck disable=SC1090
    source "${CONFIG_DIR}/config.env"
    token="${AGENT_TOKEN:-}"
  fi
  if [[ -z "${token}" && -f "${CONFIG_DIR}/agent-token" ]]; then
    token="$(cat "${CONFIG_DIR}/agent-token")"
  fi

  auth_header=()
  if [[ -n "${token}" ]]; then
    auth_header=(-H "Authorization: Bearer ${token}")
  fi

  curl -fsS --connect-timeout 10 \
    -H 'Content-Type: application/json' \
    "${auth_header[@]}" \
    -X POST "${CONTROL_PLANE_URL}/api/agent/health/first" \
    -d "${payload}" >/dev/null 2>&1 || warn "First health report failed or endpoint is not implemented yet"
}

main() {
  require_root
  parse_args "$@"
  check_os
  install_deps
  create_user_and_dirs
  download_agent
  write_config
  register_agent
  write_systemd
  write_wrapper
  start_service
  first_health_report

  log "Installation completed"
  cat <<DONE

Installed: ${AGENT_NAME}
Service:   systemctl status ${AGENT_NAME}
Logs:      journalctl -u ${AGENT_NAME} -f
Wrapper:   vpn-control-agent status
Config:    ${CONFIG_DIR}/config.env

Next step:
  In Control Plane, wait for Agent Online, then run install_protocol job.

DONE
}

main "$@"
